
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '334B263010E9494CBBE5A1FE880C2C17'
    
_lr_action_items = {'DIVIDE':([1,4,5,11,12,13,14,15,],[-6,10,-7,10,10,-8,-4,-5,]),'RPAREN':([1,4,5,8,11,12,13,14,15,],[-6,-3,-7,13,-1,-2,-8,-4,-5,]),'PLUS':([1,2,4,5,8,11,12,13,14,15,],[-6,6,-3,-7,6,-1,-2,-8,-4,-5,]),'TIMES':([1,4,5,11,12,13,14,15,],[-6,9,-7,9,9,-8,-4,-5,]),'LPAREN':([0,3,6,7,9,10,],[3,3,3,3,3,3,]),'$end':([1,2,4,5,11,12,13,14,15,],[-6,0,-3,-7,-1,-2,-8,-4,-5,]),'MINUS':([1,2,4,5,8,11,12,13,14,15,],[-6,7,-3,-7,7,-1,-2,-8,-4,-5,]),'NUM':([0,3,6,7,9,10,],[5,5,5,5,5,5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'factor':([0,3,6,7,9,10,],[1,1,1,1,14,15,]),'term':([0,3,6,7,],[4,4,11,12,]),'expr':([0,3,],[2,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> expr PLUS term','expr',3,'p_expr','2.19-2.py',31),
  ('expr -> expr MINUS term','expr',3,'p_expr','2.19-2.py',32),
  ('expr -> term','expr',1,'p_expr_term','2.19-2.py',42),
  ('term -> term TIMES factor','term',3,'p_term','2.19-2.py',49),
  ('term -> term DIVIDE factor','term',3,'p_term','2.19-2.py',50),
  ('term -> factor','term',1,'p_term_factor','2.19-2.py',60),
  ('factor -> NUM','factor',1,'p_factor','2.19-2.py',67),
  ('factor -> LPAREN expr RPAREN','factor',3,'p_factor_group','2.19-2.py',74),
]
